# <b>Why NumPy array over Python Lists</B>
## NumPy Arrays are faster than Python Lists because of the following reasons:An array is a collection of homogeneous data-types that are stored in contiguous memory locations. On the other hand, a list in Python is a collection of heterogeneous data types stored in non-contiguous memory locations.The NumPy package breaks down a task into multiple fragments and then processes all the fragments parallelly.The NumPy package integrates C, C++, and Fortran codes in Python. These programming languages have very little execution time compared to Python.

## np.newaxis :: adding an extra dimension

Effect of np.newaxis when we use it as indexing

In [23]:
import numpy as np
row = np.array([0,1,2])
row_vert = row[:, np.newaxis]
row_vert_vert = row_vert[:, np.newaxis]
row_vert_vert

array([[[0]],

       [[1]],

       [[2]]])

In [37]:
row.shape, row.ndim

((3,), 1)

In [38]:
row_vert.shape, row_vert.ndim

((3, 1), 2)

In [40]:
row_vert_vert.shape, row_vert_vert.ndim

((3, 1, 1), 3)

In [2]:
mask= np.array([1, 0, 1, 0], dtype = bool)
mask 

array([ True, False,  True, False])

In [7]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a[row_vert]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a[row_vert_vert]

array([[[[ 0,  1,  2,  3]]],


       [[[ 4,  5,  6,  7]]],


       [[[ 8,  9, 10, 11]]]])

In [42]:
a[row_vert, mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [45]:
a[row_vert_vert, mask]

array([[[ 0,  2]],

       [[ 4,  6]],

       [[ 8, 10]]])

# array.all() and arra.any()

* **`any() ::: if atleast one single value in the array is > 0 then any() will return 'True'`**
* **`all() ::: ALL the vslue of the arrsy has to be > 0, then only, all() will return 'True'`**

In [60]:
arr = 2*np.arange(0,2,0.5)
arr

array([0., 1., 2., 3.])

In [94]:
b = np.array([0,0,0,1])
c = np.array([1,1,1,0])
b.any()

True

In [95]:
c.all()

False

In the below code, 'condition' implies the situation that arr has at least one value smaller than or equal to 0.6. Which option is true wrt code and condition?

In [96]:
arr = 2*np.arange(0,2,0.5)
if np.any(arr <= 0.6):
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy")

condition satisfies


# np.squeeze() and np.expand_dims()

## Shape --> (a,b,c) means :: 
* <b> Start from the Outer Most Bracket. there will be a elements. </B><br>
* <b> then come to the inner bracket. there will be b number of elements</B><br>
* <b> then come to further inner bracket, there will be c number of elements</B>

Lets build a (3,3,1) shaped array.<br>
So, the outer most array will contain 3 ele, then the inner bracket will contain 3 ele and the inner most bracket will contain 1 ele. 

### np.squeeze(axis)

In [113]:
A = np.array([
                [[3],[1],[6]],
                [['p'],['o'],['q']],
                [['@'],['$'],['*']]
                ])
A

array([[['3'],
        ['1'],
        ['6']],

       [['p'],
        ['o'],
        ['q']],

       [['@'],
        ['$'],
        ['*']]], dtype='<U11')

In [114]:
A.shape

(3, 3, 1)

In [119]:
A1 = np.arange(9).reshape(3,3,1)
A1

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [121]:
A_dash = A.squeeze()
A_dash

array([['3', '1', '6'],
       ['p', 'o', 'q'],
       ['@', '$', '*']], dtype='<U11')

### np.expand_dims(array, axis = ())
* axis values will define at what indices, a new dimension will be added. <br>
<B>NOTE : it will add a new dimension just with single element.

In [122]:
B = np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
B.shape

(3, 3)

In [126]:
B_expanded = np.expand_dims(B, axis = 0)
B_expanded

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [134]:
B_expanded = np.expand_dims(B, axis = 1)
B_expanded

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [128]:
B_expanded = np.expand_dims(B, axis = (0,1))
B_expanded

array([[[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]])

In [129]:
B_expanded.shape

(1, 1, 3, 3)

In [137]:
np.zeros((5,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [140]:
import numpy as np
def onehot(arr):

    """
        Input arr is numpy array here
        Output an array of dimension (arr.size, max(array)+1)
    """
    result=None
    output = np.zeros((arr.size,max(arr)+1),dtype = int)

    for i,ele in enumerate(arr) :
            output[i][ele] = 1
    
    result = output
    return result

In [141]:
arr = np.array([1,2,3,4])
onehot(arr)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [143]:
a = np.array([2,3,1,4])
sum(np.exp(a))

84.7910248837216

In [2]:
import numpy as np
def softmax(data):
    '''input: data=a simple python list.
        output: a numpy array'''
        
    ans = None
    # YOUR CODE GOES HERE
    observation = np.array(data)
    score_lst = []
    for i in range(len(observation)):
        score = np.exp(observation[i]) / sum(np.exp(observation))
        score = round(score,3)
        score_lst.append(score)
    ans = np.array(score_lst)
    return ans

In [150]:
data = [9, 4, 15, 0, 17]  
softmax(data)

array([0.   , 0.   , 0.119, 0.   , 0.881])

## Concatenation of two different shaped arrays

In [18]:
A = np.array([2,3,4])
B = np.array([[6],[7],[2],[9]])
C = np.array([[5,5,5],
                [0,0,0],
                [1,1,1],
                [9,9,9]])

In [19]:
print (A.shape )
print(B.shape)
print(C.shape)

(3,)
(4, 1)
(4, 3)


In [20]:
np.concatenate((C.T,A.reshape(3,1)), axis = 1)

array([[5, 0, 1, 9, 2],
       [5, 0, 1, 9, 3],
       [5, 0, 1, 9, 4]])

## array.max()

In [48]:
import numpy as np
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
X.T.max(axis=0)

array([ 3,  7, 11])

In [50]:
[i.min() for i in X]

[0, 4, 8]

In [46]:
Y = np.array([[1,2,3],
            [9,9,9],
            [0,0,0],
            [2,2,2]])
Y.

In [47]:
Y.max(axis=1)

array([3, 9, 0, 2])

In [20]:
x = np.ones((5,5))
x[0:2,0:3] = 0
x

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
a = np.array([1,2,3,6,4,2])
for i in range(len(a)):
    a[i] = a[i]+3
a

array([4, 5, 6, 9, 7, 5])

# .argsort()

In [42]:
A = np.random.randint(1,25,size=(4,4))
A

array([[21, 22, 22,  1],
       [ 3, 24, 16,  6],
       [12,  7,  1,  6],
       [ 7, 18, 16, 20]])

In [43]:
A[A[:,2].argsort()]  # its basically sorting the value of the column 2 and then storing the indices of those values. 


array([[12,  7,  1,  6],
       [ 3, 24, 16,  6],
       [ 7, 18, 16, 20],
       [21, 22, 22,  1]])

In [49]:
A_1d = A[A % 2 == 0]
#A_1d.reshape(np.sqrt(len(A_1d),np.sqrt(len(A_1d))))
np.sqrt(len(A_1d))

3.1622776601683795

# Broadcasting

In [1]:
import numpy as np
np.arange(12).reshape(3,4) + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

So, 2 is being broadcasted into the matrix

## creating specific matrices

### np.tile()

In [2]:
np.tile(np.arange(0,3),(4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])